import { Caladea, Dancing_Script, Roboto } from 'next/font/google'
import './globals.css'
import Providers from './providers'

const caladea = Caladea({
    variable: '--font-caladea',
    subsets: ['latin'],
    weight: ['400', '700'],
})

const dancingScript = Dancing_Script({
    variable: '--font-dancing-script',
    subsets: ['vietnamese'],
    weight: ['400', '700'],
})

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin', 'vietnamese'],
    weight: ['400', '700'],
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export const viewport = {
    width: 'device-width',
    initialScale: 1,
    viewportFit: 'cover',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${caladea.variable} ${dancingScript.variable} ${roboto.variable} antialiased`}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
